import {readFile} from 'node:fs/promises';
import {escapeHtml as esc,safeUrl,markdownHtml} from './markdown.mjs';
const url=process.env.HAPPYISH_SUPABASE_URL||'https://wewucfgrtxpolxlxmitq.supabase.co';
const key=process.env.HAPPYISH_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_fNprfjd08FhOtHorM-IAjw_fJqDYSyr';
export const labels={'ai-digital-life':'AI & Digital Life',neurodiversity:'Neurodiversity','getting-unstuck':'Getting Unstuck','work-skills':'Work & Skills','digital-inclusion':'Digital Inclusion','recovery-wellbeing':'Recovery & Wellbeing',community:'Community',technology:'Technology'};
export async function posts(slug=''){
 const q=new URLSearchParams({select:'slug,title,excerpt,body_markdown,category_slug,published_at,updated_at,author_name,seo_title,meta_description,cover_image_path,cover_image_alt,sources,ai_disclosure,ai_image_disclosure,tile_colour',status:'eq.published',published_at:'lte.'+new Date().toISOString(),order:'published_at.desc',limit:'1000'});
 if(slug)q.set('slug','eq.'+slug);
 const response=await fetch(url+'/rest/v1/happyish_insights_posts?'+q,{headers:{apikey:key,Accept:'application/json'},signal:AbortSignal.timeout(12000)});
 if(!response.ok)throw new Error('Insights feed unavailable');
 return response.json();
}
function date(d){return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d))}
export function card(p){const img=safeUrl(p.cover_image_path);return `<article class="insight-card" data-colour="${esc(p.tile_colour||'yellow')}"><a href="/insights/${encodeURIComponent(p.slug)}/">${img?`<div class="insight-card-image"><img src="${esc(img)}" alt="${esc(p.cover_image_alt||'')}" loading="lazy" width="1200" height="800"></div>`:'<div class="insight-card-symbol" aria-hidden="true">✳</div>'}<div class="insight-card-copy"><p class="eyebrow">${esc(labels[p.category_slug]||p.category_slug)} · ${date(p.published_at)}</p><h2>${esc(p.title)}</h2><p>${esc(p.excerpt)}</p><span class="text-link">Read the Insight ↗</span></div></a></article>`}
async function shell(title,description,body,canonical='',schema=null){const {header,footer}=JSON.parse(await readFile(new URL('./shell.json',import.meta.url)).catch(()=>readFile(process.cwd()+'/lib/shell.json')));return `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7efdf"><title>${esc(title)} · Happyish</title><meta name="description" content="${esc(description)}">${canonical?`<link rel="canonical" href="${esc(canonical)}"><meta property="og:url" content="${esc(canonical)}">`:''}<meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="${schema?'article':'website'}">${schema?.image?`<meta property="og:image" content="${esc(schema.image)}"><meta name="twitter:card" content="summary_large_image">`:''}${schema?`<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\u003c')}</script>`:''}<link rel="stylesheet" href="/style.css?v=insights-1"><script src="/theme.js"></script></head><body>${header}${body}${footer}<script src="/app.js"></script><script src="/article.js"></script></body></html>`}
export async function handler(request){const path=new URL(request.url).pathname;const origin=process.env.HAPPYISH_SITE_URL||process.env.URL||new URL(request.url).origin;try{
 if(path==='/api/insights')return Response.json({posts:(await posts()).map(({body_markdown,...rest})=>rest)},{headers:{'Cache-Control':'public, max-age=30'}});
 if(path==='/insights-sitemap.xml'){const all=await posts();return new Response(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${all.map(p=>`<url><loc>${esc(origin+'/insights/'+p.slug+'/')}</loc><lastmod>${esc((p.updated_at||p.published_at).slice(0,10))}</lastmod></url>`).join('')}</urlset>`,{headers:{'Content-Type':'application/xml'}})}
 if(path==='/insights/archive/'||path==='/insights/archive'){const all=await posts();return new Response(await shell('Insights archive','Explore every published Happyish Insight.',`<main id="main"><section class="page-intro"><p class="eyebrow">Useful ideas. Less noise.</p><h1>The Insights library.</h1><a href="/insights.html">Search and filter Insights ↗</a></section><div class="insight-grid">${all.map(card).join('')||'<p>No Happyish Insights have been published yet.</p>'}</div></main>`,origin+'/insights/archive/'),{headers:{'Content-Type':'text/html; charset=utf-8'}})}
 const slug=path.match(/^\/insights\/([a-z0-9]+(?:-[a-z0-9]+)*)\/?$/)?.[1];if(!slug)return new Response('Not found',{status:404});
 const p=(await posts(slug))[0];if(!p)return new Response(await shell('Insight not found','This Insight is unavailable.','<main id="main"><section class="page-intro"><h1>We couldn’t find that Insight.</h1><a href="/insights.html">Back to Insights</a></section></main>'),{status:404,headers:{'Content-Type':'text/html; charset=utf-8'}});
 const image=safeUrl(p.cover_image_path),canonical=origin+'/insights/'+p.slug+'/';const schema={'@context':'https://schema.org','@type':'Article',headline:p.title,description:p.meta_description||p.excerpt,image:image||undefined,datePublished:p.published_at,dateModified:p.updated_at||p.published_at,author:{'@type':'Person',name:p.author_name},publisher:{'@type':'Organization',name:'Happyish',url:origin},mainEntityOfPage:canonical};
 const sources=(p.sources||[]).filter(s=>safeUrl(s.url)).map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.publisher||s.url)}</a>${s.publisher?' · '+esc(s.publisher):''}</li>`).join('');
 const body=`<main id="main"><section class="page-intro article-intro"><a class="text-link" href="/insights.html">← All Insights</a><p class="eyebrow">${esc(labels[p.category_slug]||p.category_slug)} · ${date(p.published_at)}</p><h1>${esc(p.title)}</h1><p class="lead">${esc(p.excerpt)}</p><p class="small">By ${esc(p.author_name)} · ${Math.max(1,Math.ceil(p.body_markdown.split(/\s+/).length/200))} minute read</p></section><div class="article-layout"><article class="insight-article">${image?`<figure class="article-cover"><img src="${esc(image)}" alt="${esc(p.cover_image_alt||'')}" width="1200" height="800">${p.ai_image_disclosure?`<figcaption class="small">${esc(p.ai_image_disclosure)}</figcaption>`:''}</figure>`:''}<div class="article-tools"><button type="button" id="article-listen">Listen to this Insight</button><button type="button" id="article-print">Print / save PDF</button><span id="listen-status" role="status" class="small"></span></div><div id="article-body">${markdownHtml(p.body_markdown)}</div>${sources?`<section class="article-sources"><h2>Sources & further reading</h2><ul>${sources}</ul></section>`:''}${p.ai_disclosure?`<aside class="article-disclosure"><p class="eyebrow">How this was made</p><p>${esc(p.ai_disclosure)}</p></aside>`:''}</article><aside class="article-rail"><p class="eyebrow">One step at a time</p><h2>Put an idea<br>into practice.</h2><p>If something here has left you with a question, we can work through it together.</p><a class="button" href="/contact.html">Need a hand? ↗</a><a class="text-link" href="/insights.html">Explore more Insights ↗</a></aside></div></main>`;
 return new Response(await shell(p.seo_title||p.title,p.meta_description||p.excerpt,body,canonical,schema),{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'public, max-age=30'}});
 }catch{return path==='/api/insights'?Response.json({error:'Insights are temporarily unavailable.'},{status:503}):new Response(await shell('Insights temporarily unavailable','Please try again shortly.','<main id="main"><section class="page-intro"><h1>A little pause.</h1><p>Insights are temporarily unavailable. Please try again shortly.</p><a href="/insights.html">Back to Insights</a></section></main>'),{status:503,headers:{'Content-Type':'text/html; charset=utf-8'}})}}
